---
keys:
  - users:
      - &louis 25209AE7B044285E
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *louis

stores:
  yaml:
    indent: 2
  json:
    indent: 2
  json_binary:
    indent: 2
