---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  update:
    desc: Update the inputs in the flake.lock file
    cmds:
      - nix flake update

  check:
    desc: Check the flake is ok
    cmds:
      - nix flake check

  list-hosts:
    desc: List the NixOS hosts in the flake
    cmds:
      - nix flake show --json 2>/dev/null | jq -r '.nixosConfigurations | keys.[]'
  list-gen:
    desc: List the NixOS generations
    cmds:
      - sudo nix-env -p /nix/var/nix/profiles/system --list-generations

  nova:build:
    desc: Build to ensure the configuration is valid
    cmds:
      - nixos-rebuild build --flake .#nova

  nova:switch:
    desc: Switch to the new configuration
    cmds:
      - nixos-rebuild switch --flake .#nova
