---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  update:
    desc: Update the inputs in the flake.lock file
    cmds:
      - nix flake update

  check:
    desc: Check the flake is ok
    cmds:
      - nix flake check

  list-hosts:
    desc: List the NixOS hosts in the flake
    cmds:
      - nix flake show --json 2>/dev/null | jq -r '.nixosConfigurations | keys.[]'
  list-gen:
    desc: List the NixOS generations
    cmds:
      - sudo nix-env -p /nix/var/nix/profiles/system --list-generations

  clean:
    desc: Clean the Nix store
    cmds:
      - home-manager expire-generations 0d
      - sudo nix-collect-garbage -d
      - nix-collect-garbage -d

  # NixOS laptop
  nova:build:
    desc: Build to ensure the configuration is valid
    cmds:
      - nixos-rebuild build --flake .#nova
  nova:switch:
    desc: Switch to the new configuration
    cmds:
      - nixos-rebuild switch --flake .#nova
  nova:update-bootloader:
    # This task is here to update the grub configuration.
    # This is only needed when the secondary have any kind of update
    # to its boot configuration (systemd-boot).
    desc: Update the bootloader
    cmds:
      - nixos-rebuild boot --flake .#nova --install-bootloader

  # NixOS laptop (secondary system)
  nebula:build:
    desc: Build to ensure the configuration is valid
    cmds:
      - nixos-rebuild build --flake .#nebula
  nebula:switch:
    desc: Switch to the new configuration
    cmds:
      - nixos-rebuild switch --flake .#nebula

  # NixOS VPN server (temporary configuration)
  vpn-server:build:
    desc: Build to ensure the configuration is valid
    cmds:
      - nixos-rebuild build --flake .#vpn-server --show-trace --verbose
  vpn-server:switch:
    desc: Switch to the new configuration
    cmds:
      - nixos-rebuild switch --flake .#vpn-server

  # Home-manager Archlinux laptop
  nova-arch:build:
    desc: Build to ensure the configuration is valid
    cmds:
      - home-manager build --flake .#nova-arch
  nova-arch:switch:
    desc: Switch to the new configuration
    cmds:
      - home-manager switch --flake .#nova-arch
