---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  update:
    desc: Update the inputs in the flake.lock file
    cmds:
      - nix flake update

  check:
    desc: Check the flake is ok
    cmds:
      - nix flake check

  list-hosts:
    desc: List the NixOS hosts in the flake
    cmds:
      - nix flake show --json 2>/dev/null | jq -r '.nixosConfigurations | keys.[]'

  build:
    desc: Dry-run build to ensure remote deployment
    cmds:
      - nixos-switch {{.NAME}} build
    requires:
      vars: ["NAME"]
