{
  username = "louis";
  userFullname = "Louis Bailleau";
  userEmail = "louis13.bailleau@gmail.com";

  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....duFJVAf3ysfy47MkNJuAc.$T3QiUA2Txoc/QR.b3CV2oehZU.vLW4TPhYqLgW4EeN1";
}
