{
  pkgs,
  myvars,
  config,
  ...
}: {
  users = {
    # Don't allow mutation of users outside the config.
    mutableUsers = false;

    groups = {
      "${myvars.username}" = {};
      docker = {};
      # for android platform tools' udev rules
      adbusers = {};
      dialout = {};
      # misc
      uinput = {};
    };

    users."${myvars.username}" = {
      # generated by `mkpasswd -m scrypt`
      inherit (myvars) initialHashedPassword;
      home = "/home/${myvars.username}";
      isNormalUser = true;
      shell = pkgs.fish;
      extraGroups = [
        myvars.username
        "users"
        "networkmanager"
        "wheel"
        "docker"
        "adbusers"
        "libvirtd"
      ];
    };

    users.root = {
      inherit (config.users.users."${myvars.username}") initialHashedPassword;
    };
  };
}
