{
  myvars,
  config,
  ...
}: {
  users = {
    # Don't allow mutation of users outside the config.
    mutableUsers = false;

    groups = {
      "${myvars.username}" = {};
      shared-data = {
        gid = 2000;
      };
      docker = {};
      # for android platform tools' udev rules
      adbusers = {};
      dialout = {};
      # misc
      uinput = {};
    };

    users."${myvars.username}" = {
      # generated by `mkpasswd -m scrypt`
      inherit (myvars) initialHashedPassword;
      hashedPassword = myvars.initialHashedPassword;
      home = "/home/${myvars.username}";
      isNormalUser = true;
      extraGroups = [
        myvars.username
        "users"
        "shared-data"
        "networkmanager"
        "wheel"
        "docker"
        "adbusers"
        "libvirtd"
      ];
    };

    users.root = {
      inherit (config.users.users."${myvars.username}") initialHashedPassword;
    };
  };
}
